"use client";

import { useLens } from "@/components/lens-provider";
import JOURNAL from "@/data/build-journal.json";
import { journalFigures } from "@/data/diagrams";
import { Figure } from "@/components/diagram/figure";

type Shipped = { repo: string; num: number; title: string; url: string };
type Metrics = {
  prs: number;
  commits: number;
  sessions: number;
  dod_met: boolean;
  dod_waived: boolean;
  correction_rounds: number;
};
type Entry = {
  date: string;
  headline: string;
  summary: string;
  curated: boolean;
  shipped: Shipped[];
  linear: string[];
  metrics: Metrics;
};

const fmtDate = (d: string) =>
  new Date(d + "T00:00:00Z").toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  });

export default function JournalPage() {
  const { lens } = useLens();
  const ed = lens === "editorial";
  const entries = JOURNAL.entries as Entry[];
  const totalPrs = entries.reduce((n, e) => n + e.metrics.prs, 0);

  return (
    <div className="mx-auto w-full max-w-3xl px-6 py-20">
      <p className="font-mono text-xs uppercase tracking-widest text-muted">
        {ed ? "The work, as it happened" : "journal"}
      </p>
      <h1
        className={
          ed
            ? "mt-4 font-display text-4xl leading-tight tracking-tight sm:text-5xl"
            : "mt-4 font-mono text-3xl font-semibold tracking-tight sm:text-4xl"
        }
      >
        {ed ? "Build journal." : "Build log, live."}
      </h1>
      <p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted">
        {entries.length} build days · {totalPrs} PRs shipped. Facts auto-assembled from git history
        and build telemetry; the summaries are curated. Nothing here asserts what the data doesn&apos;t show.
      </p>
      <p className="mt-1 font-mono text-[11px] text-muted">
        generated {new Date(JOURNAL.generated_at).toISOString().slice(0, 10)} · since {JOURNAL.since}
      </p>

      <ol className="mt-14 space-y-12 border-l border-border pl-6">
        {entries.map((e) => (
          <li key={e.date} className="relative">
            <span className="absolute -left-[27px] top-1.5 h-2 w-2 rounded-full bg-accent" />
            <div className="flex items-baseline gap-3">
              <time className="font-mono text-[11px] uppercase tracking-widest text-muted">
                {fmtDate(e.date)}
              </time>
              <RigorPills m={e.metrics} />
            </div>

            <h2
              className={
                ed
                  ? "mt-2 font-display text-xl tracking-tight sm:text-2xl"
                  : "mt-2 text-base font-semibold tracking-tight"
              }
            >
              {e.headline}
            </h2>

            {e.summary ? (
              <p className="mt-2 text-sm leading-relaxed text-fg/90">{e.summary}</p>
            ) : (
              <p className="mt-2 text-sm italic text-muted">
                Summary not yet written — facts below.
              </p>
            )}

            {journalFigures(e.date).map((f) => (
              <Figure key={f.id} id={f.id} spec={f.spec} />
            ))}

            {e.shipped.length > 0 && (
              <ul className="mt-4 space-y-1.5">
                {e.shipped.map((s) => (
                  <li key={s.repo + s.num} className="text-sm">
                    <a
                      href={s.url}
                      target="_blank"
                      rel="noreferrer"
                      className="group inline-flex items-baseline gap-2 hover:text-accent focus-visible:text-accent focus-visible:outline-none"
                    >
                      <span className="font-mono text-[11px] text-muted group-hover:text-accent">
                        {s.repo} #{s.num}
                      </span>
                      <span className="text-fg/80 group-hover:text-accent">{s.title}</span>
                    </a>
                  </li>
                ))}
              </ul>
            )}

            {e.linear.length > 0 && (
              <div className="mt-3 flex flex-wrap gap-1.5">
                {e.linear.map((ref) => (
                  <span
                    key={ref}
                    className="rounded border border-border px-1.5 py-0.5 font-mono text-[10px] uppercase tracking-wider text-muted"
                  >
                    {ref}
                  </span>
                ))}
              </div>
            )}
          </li>
        ))}
      </ol>

      <p className="mt-16 border-t border-border pt-6 font-mono text-[11px] leading-relaxed text-muted">
        Regenerated by <span className="text-fg/70">build_journal.py</span> — git + telemetry in,
        curated prose merged, zero API tokens. This is the honest V1; a fuller voice comes later.
      </p>
    </div>
  );
}

function RigorPills({ m }: { m: Metrics }) {
  const pills: { label: string; tone: "good" | "warn" | "muted" }[] = [];
  if (m.dod_met) pills.push({ label: "DoD met", tone: "good" });
  else if (m.dod_waived) pills.push({ label: "DoD waived", tone: "warn" });
  if (m.correction_rounds > 0)
    pills.push({ label: `${m.correction_rounds} correction${m.correction_rounds > 1 ? "s" : ""}`, tone: "muted" });
  if (m.prs > 0) pills.push({ label: `${m.prs} PR${m.prs > 1 ? "s" : ""}`, tone: "muted" });

  if (pills.length === 0) return null;
  return (
    <div className="flex flex-wrap gap-1.5">
      {pills.map((p) => (
        <span
          key={p.label}
          className={
            "rounded-full px-2 py-0.5 font-mono text-[10px] tracking-wide " +
            (p.tone === "good"
              ? "bg-accent/10 text-accent"
              : p.tone === "warn"
                ? "bg-amber-500/10 text-amber-600 dark:text-amber-400"
                : "border border-border text-muted")
          }
        >
          {p.label}
        </span>
      ))}
    </div>
  );
}
