// The figure registry and where each figure appears. Figures attach by key rather than as fields on
// the content files: build-journal.json is regenerated by a hook, and build-arcs.json is shared with
// the Artifact generator, so edits there would be overwritten or break a consumer.
import type { DiagramSpec } from "@/components/diagram/types";
import { INTELLIGENCE_ARC_FIGURES } from "./arcs-intelligence";
import { RIGOR_ARC_FIGURES } from "./arcs-rigor";
import { HISTORY_FIGURES } from "./changelog-history";
import { RECENT_FIGURES } from "./changelog-recent";
import { JOURNAL_FIGURES_A } from "./journal-a";
import { JOURNAL_FIGURES_B } from "./journal-b";
import { SYSTEM_FIGURES } from "./system";

export const FIGURES = {
  ...SYSTEM_FIGURES,
  ...INTELLIGENCE_ARC_FIGURES,
  ...RIGOR_ARC_FIGURES,
  ...RECENT_FIGURES,
  ...HISTORY_FIGURES,
  ...JOURNAL_FIGURES_A,
  ...JOURNAL_FIGURES_B,
} satisfies Record<string, DiagramSpec>;

export type FigureId = keyof typeof FIGURES;

/** A figure plus a DOM scope unique to where it's placed (it namespaces the SVG marker ids). */
export type Placed = { id: string; spec: DiagramSpec };

const place = (scope: string, figure: FigureId): Placed => ({ id: `${scope}-${figure}`, spec: FIGURES[figure] });

/** Changelog entries, keyed "date|title" — the entries carry no ids of their own. */
const CHANGELOG: Record<string, FigureId> = {
  "2026-09-12|Reconciliation as a role": "reconciliation-charter",
  "2026-09-12|Sessions, not branches": "sessions-not-branches",
  "2026-09-12|Telemetry that cannot conflict": "telemetry-shards",
  "2026-09-12|ADR correction + extractor self-test": "adr8-correction",
  "2026-09-12|Rigor that watches itself": "graph-watches",
  "2026-09-12|Reference check stops misfiring": "ref-check-templates",
  "2026-09-12|The inbox as a signal source": "inbox-miner",
  "2026-09-11|Event posts become one arc": "event-post-arc",
  "2026-07-31|Toolbox generator": "toolbox-generator",
  "2026-07-30|Live operator dashboards": "ops-dashboards",
  "2026-07-17|Cross-provider judge": "cross-provider-judge",
  "2026-06-25|Build-rigor + measurement layer": "build-rigor-measurement",
  "2026-06-12|Empire State Hub": "empire-state-hub",
  "2026-06-11|Execution-focus window closed": "execution-focus",
  "2026-05-30|Voice system v0.5": "voice-stance",
  "2026-05-28|Post-event brief as canonical store": "brief-canonical-store",
  "2026-05-26|Visual briefs + source discipline": "source-check",
  "2026-05-21|/post-event-content": "workflow-b-v1",
  "2026-05-20|/check-new-events": "check-new-events",
  "2026-05-13|Systems-thinking harness": "systems-harness",
  "2026-05-07|Orchestrator → synthesizer pivot": "fanout-constraint",
  "2026-05-04|Multi-agent rebuild": "multi-agent-rebuild",
  "2026-04-09|Pipeline, take 3": "take-3",
};

/**
 * Journal days, keyed by date. 08-12 and 08-13 are uncurated roadmap/export housekeeping with no
 * mechanism to draw; 07-22 is the same dual-judge ship as 07-21, drawn once there.
 */
const JOURNAL: Record<string, FigureId[]> = {
  "2026-09-12": ["sessions-not-branches", "graph-watches", "batch-tiering"],
  "2026-09-11": ["event-post-arc", "kb-retrieval"],
  "2026-09-09": ["table-set"],
  "2026-09-08": ["role-radar"],
  "2026-08-31": ["signal-stream"],
  "2026-08-28": ["steering-v2"],
  "2026-08-25": ["deep-read-gate"],
  "2026-08-21": ["brief-two-layers"],
  "2026-08-11": ["prior-context"],
  "2026-08-10": ["expand-contract"],
  "2026-08-07": ["journal-generator", "arcs-canonical"],
  "2026-08-06": ["progressive-trend-engine"],
  "2026-08-05": ["branch-first-governance"],
  "2026-07-31": ["three-layer-program", "toolbox-generator"],
  "2026-07-30": ["ops-dashboards"],
  "2026-07-21": ["cross-provider-judge"],
  "2026-07-17": ["judge-calibration"],
  "2026-07-15": ["command-skeleton"],
  "2026-07-11": ["build-rigor-measurement"],
};

export function changelogFigure(date: string, title: string): Placed | null {
  const figure = CHANGELOG[`${date}|${title}`];
  return figure ? place(`changelog-${date}`, figure) : null;
}

export function journalFigures(date: string): Placed[] {
  return (JOURNAL[date] ?? []).map((figure) => place(`journal-${date}`, figure));
}

/** Build arcs share their id with their figure. */
export function arcFigure(arcId: string): Placed | null {
  return arcId in FIGURES ? place("arc", arcId as FigureId) : null;
}

export function pageFigure(scope: string, figure: FigureId): Placed {
  return place(scope, figure);
}
